backend:
  name: git-gateway

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"
collections:
  - name: "recipe"
    label: "Recipe"
    folder: "site/content/recipes"
    slug: "_index.{{ language }}"
    create: true
    fields:
      - {label: "Visible", name: "visible", widget: "boolean", default: false, required: false}
      - {label: "Content Type", name: "contenttype", widget: "hidden", default: "section"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "de"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
    editor:
      -preview: false

DefaultContentLanguage: en
languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 1
  de:
    contentDir: content/deutsche
    languageName: Deutsche
    weight: 2
